[package]
name = "rssplit"
version = "0.1.0"
authors = ["thepotatocoder <dbviana733@gmail.com>"]

[[bin]]
name = "rssplit"
path = "src/bin/main.rs"

[dependencies]
clap = {version = "2.19", features = ["yaml"]}
grep = "0.1.7"
lazy_static = "0.2"
unindent = "0.1.2"

